// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specifies options for controlling advanced machine features.
public struct AdvancedMachineFeatures: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Whether to enable nested virtualization or not (default is
  /// false).
  public var enableNestedVirtualization: Swift.Bool? = nil

  /// Optional. The number of threads per physical core. To disable simultaneous
  /// multithreading (SMT) set this to 1. If unset, the maximum number
  /// of threads supported per core by the underlying processor is
  /// assumed.
  public var threadsPerCore: Swift.Int32? = nil

  /// Optional. The number of physical cores to expose to an instance. Multiply
  /// by the number of threads per core to compute the total number of virtual
  /// CPUs to expose to the instance. If unset, the number of cores is
  /// inferred from the instance's nominal CPU count and the underlying
  /// platform's SMT width.
  public var visibleCoreCount: Swift.Int32? = nil

  /// Optional. Whether to enable UEFI networking for instance creation.
  public var enableUefiNetworking: Swift.Bool? = nil

  /// Initialize a new instance of `AdvancedMachineFeatures`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdvancedMachineFeatures().with { $0.enableNestedVirtualization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AdvancedMachineFeatures"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
