// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies the reservations that this instance can consume from.
public struct AllocationAffinity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Specifies the type of reservation from which this instance can
  /// consume
  public var consumeAllocationType: AllocationAffinity.Type_? = nil

  /// Optional. Corresponds to the label key of a reservation resource.
  public var key: Swift.String? = nil

  /// Optional. Corresponds to the label values of a reservation resource.
  public var values: [Swift.String] = []

  /// Initialize a new instance of `AllocationAffinity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllocationAffinity().with { $0.consumeAllocationType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case consumeAllocationType = "consumeReservationType"
    case key = "key"
    case values = "values"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.consumeAllocationType = try container.decodeIfPresent(
      AllocationAffinity.Type_.self, forKey: .consumeAllocationType)
    self.key = try container.decodeIfPresent(Swift.String.self, forKey: .key)
    self.values = try container.decode([Swift.String].self, forKey: .values)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.consumeAllocationType, forKey: .consumeAllocationType)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.values, forKey: .values)
  }

  /// Indicates whether to consume from a reservation or not.
  public enum Type_: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Do not consume from any allocated capacity.
    case noReservation
    /// Consume any allocation available.
    case anyReservation
    /// Must consume from a specific reservation. Must specify key value fields
    /// for specifying the reservations.
    case specificReservation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noReservation: return 1
      case .anyReservation: return 2
      case .specificReservation: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .noReservation: return "NO_RESERVATION"
      case .anyReservation: return "ANY_RESERVATION"
      case .specificReservation: return "SPECIFIC_RESERVATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "NO_RESERVATION": self = .noReservation
      case "ANY_RESERVATION": self = .anyReservation
      case "SPECIFIC_RESERVATION": self = .specificReservation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noReservation
      case 2: self = .anyReservation
      case 3: self = .specificReservation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .noReservation: return try container.encode(1)
      case .anyReservation: return try container.encode(2)
      case .specificReservation: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AllocationAffinity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
