// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// AlloyDbClusterBackupProperties represents AlloyDB cluster
/// backup properties.
/// .
public struct AlloyDbClusterBackupProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// An optional text description for the backup.
  public var description: Swift.String? = nil

  /// Output only. Storage usage of this particular backup
  public var storedBytes: Swift.Int64 = Swift.Int64()

  /// Output only. The chain id of this backup. Backups belonging to the same
  /// chain are sharing the same chain id. This property is calculated and
  /// maintained by BackupDR.
  public var chainId: Swift.String = Swift.String()

  /// Output only. The PostgreSQL major version of the AlloyDB cluster when the
  /// backup was taken.
  public var databaseVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `AlloyDbClusterBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AlloyDbClusterBackupProperties().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AlloyDbClusterBackupProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
