// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing a BackupVault object.
public struct BackupVault: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the backup vault to create. It must have
  /// the
  /// format`"projects/{project}/locations/{location}/backupVaults/{backupvault}"`.
  /// `{backupvault}` cannot be changed after creation. It must be between 3-63
  /// characters long and must be unique within the project and location.
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the BackupVault instance (2048 characters or
  /// less).
  public var description: Swift.String? = nil

  /// Optional. Resource labels to represent user provided metadata.
  /// No labels currently defined:
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the instance was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. The default and minimum enforced retention for each backup within
  /// the backup vault.  The enforced retention for each backup can be extended.
  public var backupMinimumEnforcedRetentionDuration: GoogleCloudWkt.Duration? = nil

  /// Optional. Setting for how a backup's enforced retention end time is
  /// inherited.
  public var backupRetentionInheritance: BackupVault.BackupRetentionInheritance? = nil

  /// Output only. Set to true when there are no backups nested under this
  /// resource.
  public var deletable: Swift.Bool? = nil

  /// Optional. Server specified ETag for the backup vault resource to
  /// prevent simultaneous updates from overwiting each other.
  public var etag: Swift.String? = nil

  /// Output only. The BackupVault resource instance state.
  public var state: BackupVault.State = BackupVault.State()

  /// Optional. Time after which the BackupVault resource is locked.
  public var effectiveTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The number of backups in this backup vault.
  public var backupCount: Swift.Int64 = Swift.Int64()

  /// Output only. Service account used by the BackupVault Service for this
  /// BackupVault.  The user should grant this account permissions in their
  /// workload project to enable the service to run backups and restores there.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. Total size of the storage used by all backup resources.
  public var totalStoredBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Immutable after resource creation until resource deletion.
  public var uid: Swift.String = Swift.String()

  /// Optional. User annotations. See https://google.aip.dev/128#annotations
  /// Stores small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Restricts access to certain sources and destinations for data
  /// being sent into, or restored from, the backup vault.
  /// Defaults to WITHIN_ORGANIZATION if not provided during creation.
  public var accessRestriction: BackupVault.AccessRestriction = BackupVault.AccessRestriction()

  /// Optional. The encryption config of the backup vault.
  public var encryptionConfig: BackupVault.EncryptionConfig? = nil

  /// Initialize a new instance of `BackupVault`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupVault().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Message describing the EncryptionConfig of backup vault.
  /// This determines how data within the vault is encrypted at rest.
  public struct EncryptionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS key name to encrypt backups in this backup vault.
    /// Must be in the same region as the vault. Some workload backups like
    /// compute disk backups may use their inherited source key instead. Format:
    /// projects/{project}/locations/{location}/keyRings/{ring}/cryptoKeys/{key}
    public var kmsKeyName: Swift.String? = nil

    /// Initialize a new instance of `EncryptionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EncryptionConfig().with { $0.kmsKeyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.backupdr.v1.BackupVault.EncryptionConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// How a backup's enforced retention end time is inherited.
  public enum BackupRetentionInheritance: Codable, Equatable, Sendable {
    /// Inheritance behavior not set. This will default to
    /// `INHERIT_VAULT_RETENTION`.
    case unspecified
    /// The enforced retention end time of a backup will be inherited from the
    /// backup vault's `backup_minimum_enforced_retention_duration` field.
    ///
    /// This is the default behavior.
    case inheritVaultRetention
    /// The enforced retention end time of a backup will always match the expire
    /// time of the backup.
    ///
    /// If this is set, the backup's enforced retention end time will be set to
    /// match the expire time during creation of the backup. When updating, the
    /// ERET and expire time must be updated together and have the same value.
    /// Invalid update requests will be rejected by the server.
    case matchBackupExpireTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inheritVaultRetention: return 1
      case .matchBackupExpireTime: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_RETENTION_INHERITANCE_UNSPECIFIED"
      case .inheritVaultRetention: return "INHERIT_VAULT_RETENTION"
      case .matchBackupExpireTime: return "MATCH_BACKUP_EXPIRE_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupRetentionInheritance/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_RETENTION_INHERITANCE_UNSPECIFIED": self = .unspecified
      case "INHERIT_VAULT_RETENTION": self = .inheritVaultRetention
      case "MATCH_BACKUP_EXPIRE_TIME": self = .matchBackupExpireTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupRetentionInheritance/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inheritVaultRetention
      case 2: self = .matchBackupExpireTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inheritVaultRetention: return try container.encode(1)
      case .matchBackupExpireTime: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Holds the state of the backup vault resource.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// The backup vault is being created.
    case creating
    /// The backup vault has been created and is fully usable.
    case active
    /// The backup vault is being deleted.
    case deleting
    /// The backup vault is experiencing an issue and might be unusable.
    case error
    /// The backup vault is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Holds the access restriction for the backup vault.
  public enum AccessRestriction: Codable, Equatable, Sendable {
    /// Access restriction not set. If user does not provide any value or pass
    /// this value, it will be changed to WITHIN_ORGANIZATION.
    case unspecified
    /// Access to or from resources outside your current project will be denied.
    case withinProject
    /// Access to or from resources outside your current organization will be
    /// denied.
    case withinOrganization
    /// No access restriction.
    case unrestricted
    /// Access to or from resources outside your current organization will be
    /// denied except for backup appliance.
    case withinOrgButUnrestrictedForBa
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .withinProject: return 1
      case .withinOrganization: return 2
      case .unrestricted: return 3
      case .withinOrgButUnrestrictedForBa: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCESS_RESTRICTION_UNSPECIFIED"
      case .withinProject: return "WITHIN_PROJECT"
      case .withinOrganization: return "WITHIN_ORGANIZATION"
      case .unrestricted: return "UNRESTRICTED"
      case .withinOrgButUnrestrictedForBa: return "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccessRestriction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCESS_RESTRICTION_UNSPECIFIED": self = .unspecified
      case "WITHIN_PROJECT": self = .withinProject
      case "WITHIN_ORGANIZATION": self = .withinOrganization
      case "UNRESTRICTED": self = .unrestricted
      case "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA": self = .withinOrgButUnrestrictedForBa
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccessRestriction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .withinProject
      case 2: self = .withinOrganization
      case 3: self = .unrestricted
      case 4: self = .withinOrgButUnrestrictedForBa
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .withinProject: return try container.encode(1)
      case .withinOrganization: return try container.encode(2)
      case .unrestricted: return try container.encode(3)
      case .withinOrgButUnrestrictedForBa: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupVault"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
