// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing a Backup object.
public struct Backup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the backup to create. It must have the
  /// format`"projects/<project>/locations/<location>/backupVaults/<backupvault>/dataSources/{datasource}/backups/{backup}"`.
  /// `{backup}` cannot be changed after creation. It must be between 3-63
  /// characters long and must be unique within the datasource.
  public var name: Swift.String = Swift.String()

  /// Output only. The description of the Backup instance (2048 characters or
  /// less).
  public var description: Swift.String? = nil

  /// Output only. The time when the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the instance was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Resource labels to represent user provided metadata.
  /// No labels currently defined.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The backup can not be deleted before this time.
  public var enforcedRetentionEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Setting for how the enforced retention end time is inherited.
  /// This value is copied from this backup's BackupVault.
  public var backupRetentionInheritance: BackupVault.BackupRetentionInheritance? = nil

  /// Optional. When this backup is automatically expired.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The point in time when this backup was captured from the
  /// source.
  public var consistencyTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Server specified ETag to prevent updates from overwriting each
  /// other.
  public var etag: Swift.String? = nil

  /// Output only. The Backup resource instance state.
  public var state: Backup.State = Backup.State()

  /// Output only. The list of BackupLocks taken by the service to prevent the
  /// deletion of the backup.
  public var serviceLocks: [BackupLock] = []

  /// Optional. The list of BackupLocks taken by the accessor Backup Appliance.
  public var backupApplianceLocks: [BackupLock] = []

  /// Output only. Type of the backup, unspecified, scheduled or ondemand.
  public var backupType: Backup.BackupType = Backup.BackupType()

  /// Output only. source resource size in bytes at the time of the backup.
  public var resourceSizeBytes: Swift.Int64 = Swift.Int64()

  /// Optional. Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Optional. Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool? = nil

  /// Optional. Output only. The list of KMS key versions used to encrypt the
  /// backup.
  public var kmsKeyVersions: [Swift.String] = []

  /// Workload specific backup properties.
  public var backupProperties: OneOf_BackupProperties? = nil

  /// Configuration Info has the resource format-specific configuration.
  public var planInfo: OneOf_PlanInfo? = nil

  /// Resource that is being backed up.
  public var sourceResource: OneOf_SourceResource? = nil

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case description = "description"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case enforcedRetentionEndTime = "enforcedRetentionEndTime"
    case backupRetentionInheritance = "backupRetentionInheritance"
    case expireTime = "expireTime"
    case consistencyTime = "consistencyTime"
    case etag = "etag"
    case state = "state"
    case serviceLocks = "serviceLocks"
    case backupApplianceLocks = "backupApplianceLocks"
    case computeInstanceBackupProperties = "computeInstanceBackupProperties"
    case cloudSqlInstanceBackupProperties = "cloudSqlInstanceBackupProperties"
    case backupApplianceBackupProperties = "backupApplianceBackupProperties"
    case alloyDbBackupProperties = "alloyDbBackupProperties"
    case diskBackupProperties = "diskBackupProperties"
    case backupType = "backupType"
    case gcpBackupPlanInfo = "gcpBackupPlanInfo"
    case resourceSizeBytes = "resourceSizeBytes"
    case satisfiesPzs = "satisfiesPzs"
    case satisfiesPzi = "satisfiesPzi"
    case gcpResource = "gcpResource"
    case kmsKeyVersions = "kmsKeyVersions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.enforcedRetentionEndTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .enforcedRetentionEndTime)
    self.backupRetentionInheritance = try container.decodeIfPresent(
      BackupVault.BackupRetentionInheritance.self, forKey: .backupRetentionInheritance)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .expireTime)
    self.consistencyTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .consistencyTime)
    self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
    self.state = try container.decode(Backup.State.self, forKey: .state)
    self.serviceLocks = try container.decode([BackupLock].self, forKey: .serviceLocks)
    self.backupApplianceLocks = try container.decode(
      [BackupLock].self, forKey: .backupApplianceLocks)
    self.backupType = try container.decode(Backup.BackupType.self, forKey: .backupType)
    self.resourceSizeBytes = try container.decode(Swift.Int64.self, forKey: .resourceSizeBytes)
    self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
    self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)
    self.kmsKeyVersions = try container.decode([Swift.String].self, forKey: .kmsKeyVersions)

    var backupProperties: OneOf_BackupProperties? = nil
    let backupPropertiesCheckAndSet = {
      if backupProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'backupProperties'"))
      }
      backupProperties = $0
    }
    if let computeInstanceBackupProperties = try container.decodeIfPresent(
      ComputeInstanceBackupProperties?.self, forKey: .computeInstanceBackupProperties)
    {
      try backupPropertiesCheckAndSet(
        .computeInstanceBackupProperties(computeInstanceBackupProperties))
    }
    if let cloudSqlInstanceBackupProperties = try container.decodeIfPresent(
      CloudSqlInstanceBackupProperties?.self, forKey: .cloudSqlInstanceBackupProperties)
    {
      try backupPropertiesCheckAndSet(
        .cloudSqlInstanceBackupProperties(cloudSqlInstanceBackupProperties))
    }
    if let backupApplianceBackupProperties = try container.decodeIfPresent(
      BackupApplianceBackupProperties?.self, forKey: .backupApplianceBackupProperties)
    {
      try backupPropertiesCheckAndSet(
        .backupApplianceBackupProperties(backupApplianceBackupProperties))
    }
    if let alloyDbBackupProperties = try container.decodeIfPresent(
      AlloyDbClusterBackupProperties?.self, forKey: .alloyDbBackupProperties)
    {
      try backupPropertiesCheckAndSet(.alloyDbBackupProperties(alloyDbBackupProperties))
    }
    if let diskBackupProperties = try container.decodeIfPresent(
      DiskBackupProperties?.self, forKey: .diskBackupProperties)
    {
      try backupPropertiesCheckAndSet(.diskBackupProperties(diskBackupProperties))
    }
    self.backupProperties = backupProperties

    var planInfo: OneOf_PlanInfo? = nil
    let planInfoCheckAndSet = {
      if planInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'planInfo'"))
      }
      planInfo = $0
    }
    if let gcpBackupPlanInfo = try container.decodeIfPresent(
      Backup.GCPBackupPlanInfo?.self, forKey: .gcpBackupPlanInfo)
    {
      try planInfoCheckAndSet(.gcpBackupPlanInfo(gcpBackupPlanInfo))
    }
    self.planInfo = planInfo

    var sourceResource: OneOf_SourceResource? = nil
    let sourceResourceCheckAndSet = {
      if sourceResource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceResource'"))
      }
      sourceResource = $0
    }
    if let gcpResource = try container.decodeIfPresent(
      BackupGcpResource?.self, forKey: .gcpResource)
    {
      try sourceResourceCheckAndSet(.gcpResource(gcpResource))
    }
    self.sourceResource = sourceResource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.enforcedRetentionEndTime, forKey: .enforcedRetentionEndTime)
    try container.encode(self.backupRetentionInheritance, forKey: .backupRetentionInheritance)
    try container.encode(self.expireTime, forKey: .expireTime)
    try container.encode(self.consistencyTime, forKey: .consistencyTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.serviceLocks, forKey: .serviceLocks)
    try container.encode(self.backupApplianceLocks, forKey: .backupApplianceLocks)
    try container.encode(self.backupType, forKey: .backupType)
    try container.encode(self.resourceSizeBytes, forKey: .resourceSizeBytes)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.kmsKeyVersions, forKey: .kmsKeyVersions)

    if let choice = self.backupProperties {
      switch choice {
      case .computeInstanceBackupProperties(let value):
        try container.encode(value, forKey: .computeInstanceBackupProperties)
      case .cloudSqlInstanceBackupProperties(let value):
        try container.encode(value, forKey: .cloudSqlInstanceBackupProperties)
      case .backupApplianceBackupProperties(let value):
        try container.encode(value, forKey: .backupApplianceBackupProperties)
      case .alloyDbBackupProperties(let value):
        try container.encode(value, forKey: .alloyDbBackupProperties)
      case .diskBackupProperties(let value):
        try container.encode(value, forKey: .diskBackupProperties)
      }
    }

    if let choice = self.planInfo {
      switch choice {
      case .gcpBackupPlanInfo(let value):
        try container.encode(value, forKey: .gcpBackupPlanInfo)
      }
    }

    if let choice = self.sourceResource {
      switch choice {
      case .gcpResource(let value):
        try container.encode(value, forKey: .gcpResource)
      }
    }
  }

  /// GCPBackupPlanInfo captures the plan configuration details of Google Cloud
  /// resources at the time of backup.
  public struct GCPBackupPlanInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Resource name of backup plan by which workload is protected at the time
    /// of the backup.
    /// Format:
    /// projects/{project}/locations/{location}/backupPlans/{backupPlanId}
    public var backupPlan: Swift.String = Swift.String()

    /// The rule id of the backup plan which triggered this backup in case of
    /// scheduled backup or used for
    public var backupPlanRuleId: Swift.String = Swift.String()

    /// Resource name of the backup plan revision which triggered this backup in
    /// case of scheduled backup or used for on demand backup.
    /// Format:
    /// projects/{project}/locations/{location}/backupPlans/{backupPlanId}/revisions/{revisionId}
    public var backupPlanRevisionName: Swift.String = Swift.String()

    /// The user friendly id of the backup plan revision which triggered this
    /// backup in case of scheduled backup or used for on demand backup.
    public var backupPlanRevisionId: Swift.String = Swift.String()

    /// Initialize a new instance of `GCPBackupPlanInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GCPBackupPlanInfo().with { $0.backupPlan = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.backupdr.v1.Backup.GCPBackupPlanInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Holds the state of the backup resource.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// The backup is being created.
    case creating
    /// The backup has been created and is fully usable.
    case active
    /// The backup is being deleted.
    case deleting
    /// The backup is experiencing an issue and might be unusable.
    case error
    /// The backup is being uploaded.
    case uploading
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .error: return 4
      case .uploading: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .uploading: return "UPLOADING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPLOADING": self = .uploading
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .uploading
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .uploading: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of the backup, scheduled or ondemand.
  public enum BackupType: Codable, Equatable, Sendable {
    /// Backup type is unspecified.
    case unspecified
    /// Scheduled backup.
    case scheduled
    /// On demand backup.
    case onDemand
    /// Operational backup.
    case onDemandOperational
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .onDemand: return 2
      case .onDemandOperational: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_TYPE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .onDemand: return "ON_DEMAND"
      case .onDemandOperational: return "ON_DEMAND_OPERATIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_TYPE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "ON_DEMAND": self = .onDemand
      case "ON_DEMAND_OPERATIONAL": self = .onDemandOperational
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .onDemand
      case 3: self = .onDemandOperational
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .scheduled: return try container.encode(1)
      case .onDemand: return try container.encode(2)
      case .onDemandOperational: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Workload specific backup properties.
  public enum OneOf_BackupProperties: Codable, Equatable, Sendable {
    /// Output only. Compute Engine specific backup properties.
    indirect case computeInstanceBackupProperties(ComputeInstanceBackupProperties?)
    /// Output only. Cloud SQL specific backup properties.
    indirect case cloudSqlInstanceBackupProperties(CloudSqlInstanceBackupProperties?)
    /// Output only. Backup Appliance specific backup properties.
    indirect case backupApplianceBackupProperties(BackupApplianceBackupProperties?)
    /// Output only. AlloyDB specific backup properties.
    indirect case alloyDbBackupProperties(AlloyDbClusterBackupProperties?)
    /// Output only. Disk specific backup properties.
    indirect case diskBackupProperties(DiskBackupProperties?)
  }

  /// Configuration Info has the resource format-specific configuration.
  public enum OneOf_PlanInfo: Codable, Equatable, Sendable {
    /// Output only. Configuration for a Google Cloud resource.
    indirect case gcpBackupPlanInfo(Backup.GCPBackupPlanInfo?)
  }

  /// Resource that is being backed up.
  public enum OneOf_SourceResource: Codable, Equatable, Sendable {
    /// Output only. Unique identifier of the GCP resource that is being backed
    /// up.
    indirect case gcpResource(BackupGcpResource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.Backup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
