// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// BackupApplianceLockInfo contains metadata about the backupappliance that
/// created the lock.
public struct BackupApplianceLockInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The ID of the backup/recovery appliance that created this lock.
  public var backupApplianceId: Swift.Int64 = Swift.Int64()

  /// Required. The name of the backup/recovery appliance that created this lock.
  public var backupApplianceName: Swift.String = Swift.String()

  /// Required. The reason for the lock: e.g. MOUNT/RESTORE/BACKUP/etc.  The
  /// value of this string is only meaningful to the client and it is not
  /// interpreted by the BackupVault service.
  public var lockReason: Swift.String = Swift.String()

  /// The information about this lock.
  public var lockSource: OneOf_LockSource? = nil

  /// Initialize a new instance of `BackupApplianceLockInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupApplianceLockInfo().with { $0.backupApplianceId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case backupApplianceId = "backupApplianceId"
    case backupApplianceName = "backupApplianceName"
    case lockReason = "lockReason"
    case jobName = "jobName"
    case backupImage = "backupImage"
    case slaId = "slaId"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.backupApplianceId = try container.decode(Swift.Int64.self, forKey: .backupApplianceId)
    self.backupApplianceName = try container.decode(Swift.String.self, forKey: .backupApplianceName)
    self.lockReason = try container.decode(Swift.String.self, forKey: .lockReason)

    var lockSource: OneOf_LockSource? = nil
    let lockSourceCheckAndSet = {
      if lockSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'lockSource'"))
      }
      lockSource = $0
    }
    if let jobName = try container.decodeIfPresent(Swift.String.self, forKey: .jobName) {
      try lockSourceCheckAndSet(.jobName(jobName))
    }
    if let backupImage = try container.decodeIfPresent(Swift.String.self, forKey: .backupImage) {
      try lockSourceCheckAndSet(.backupImage(backupImage))
    }
    if let slaId = try container.decodeIfPresent(Swift.Int64.self, forKey: .slaId) {
      try lockSourceCheckAndSet(.slaId(slaId))
    }
    self.lockSource = lockSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupApplianceId, forKey: .backupApplianceId)
    try container.encode(self.backupApplianceName, forKey: .backupApplianceName)
    try container.encode(self.lockReason, forKey: .lockReason)

    if let choice = self.lockSource {
      switch choice {
      case .jobName(let value):
        try container.encode(value, forKey: .jobName)
      case .backupImage(let value):
        try container.encode(value, forKey: .backupImage)
      case .slaId(let value):
        try container.encode(value, forKey: .slaId)
      }
    }
  }

  /// The information about this lock.
  public enum OneOf_LockSource: Codable, Equatable, Sendable {
    /// The job name on the backup/recovery appliance that created this lock.
    case jobName(Swift.String)
    /// The image name that depends on this Backup.
    case backupImage(Swift.String)
    /// The SLA on the backup/recovery appliance that owns the lock.
    case slaId(Swift.Int64)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupApplianceLockInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
