// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol BackupDRStub: Sendable {
    func listManagementServers(
      request: ListManagementServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListManagementServersResponse

    func getManagementServer(
      request: GetManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ManagementServer

    func createManagementServer(
      request: CreateManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteManagementServer(
      request: DeleteManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackupVault(
      request: CreateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackupVaults(
      request: ListBackupVaultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupVaultsResponse

    func fetchUsableBackupVaults(
      request: FetchUsableBackupVaultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchUsableBackupVaultsResponse

    func getBackupVault(
      request: GetBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupVault

    func updateBackupVault(
      request: UpdateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackupVault(
      request: DeleteBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourcesResponse

    func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSource

    func updateDataSource(
      request: UpdateDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupsResponse

    func fetchBackupsForResourceType(
      request: FetchBackupsForResourceTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupsForResourceTypeResponse

    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.Backup

    func updateBackup(
      request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func restoreBackup(
      request: RestoreBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createBackupPlan(
      request: CreateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateBackupPlan(
      request: UpdateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackupPlan(
      request: GetBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlan

    func listBackupPlans(
      request: ListBackupPlansRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlansResponse

    func deleteBackupPlan(
      request: DeleteBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackupPlanRevision(
      request: GetBackupPlanRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanRevision

    func listBackupPlanRevisions(
      request: ListBackupPlanRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanRevisionsResponse

    func createBackupPlanAssociation(
      request: CreateBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateBackupPlanAssociation(
      request: UpdateBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getBackupPlanAssociation(
      request: GetBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanAssociation

    func listBackupPlanAssociations(
      request: ListBackupPlanAssociationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanAssociationsResponse

    func fetchBackupPlanAssociationsForResourceType(
      request: FetchBackupPlanAssociationsForResourceTypeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupPlanAssociationsForResourceTypeResponse

    func deleteBackupPlanAssociation(
      request: DeleteBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func triggerBackup(
      request: TriggerBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDataSourceReference(
      request: GetDataSourceReferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSourceReference

    func listDataSourceReferences(
      request: ListDataSourceReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourceReferencesResponse

    func fetchDataSourceReferencesForResourceType(
      request: FetchDataSourceReferencesForResourceTypeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchDataSourceReferencesForResourceTypeResponse

    func initializeService(
      request: InitializeServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
