// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class BackupDRRetry: BackupDRStub {
    let inner: any BackupDRStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any BackupDRStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listManagementServers(
      request: ListManagementServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListManagementServersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListManagementServersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListManagementServersResponse
          in
          return try await self.inner.listManagementServers(request: r, options: o)
        })
    }

    public func getManagementServer(
      request: GetManagementServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ManagementServer {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetManagementServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ManagementServer
          in
          return try await self.inner.getManagementServer(request: r, options: o)
        })
    }

    public func createManagementServer(
      request: CreateManagementServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateManagementServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createManagementServer(request: r, options: o)
        })
    }

    public func deleteManagementServer(
      request: DeleteManagementServerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteManagementServerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteManagementServer(request: r, options: o)
        })
    }

    public func createBackupVault(
      request: CreateBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupVault(request: r, options: o)
        })
    }

    public func listBackupVaults(
      request: ListBackupVaultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupVaultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupVaultsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupVaultsResponse
          in
          return try await self.inner.listBackupVaults(request: r, options: o)
        })
    }

    public func fetchUsableBackupVaults(
      request: FetchUsableBackupVaultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchUsableBackupVaultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchUsableBackupVaultsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.FetchUsableBackupVaultsResponse
          in
          return try await self.inner.fetchUsableBackupVaults(request: r, options: o)
        })
    }

    public func getBackupVault(
      request: GetBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupVault {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupVault
          in
          return try await self.inner.getBackupVault(request: r, options: o)
        })
    }

    public func updateBackupVault(
      request: UpdateBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupVault(request: r, options: o)
        })
    }

    public func deleteBackupVault(
      request: DeleteBackupVaultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupVaultRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupVault(request: r, options: o)
        })
    }

    public func listDataSources(
      request: ListDataSourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDataSourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListDataSourcesResponse
          in
          return try await self.inner.listDataSources(request: r, options: o)
        })
    }

    public func getDataSource(
      request: GetDataSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSource {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDataSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.DataSource
          in
          return try await self.inner.getDataSource(request: r, options: o)
        })
    }

    public func updateDataSource(
      request: UpdateDataSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDataSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDataSource(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func fetchBackupsForResourceType(
      request: FetchBackupsForResourceTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupsForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchBackupsForResourceTypeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.FetchBackupsForResourceTypeResponse
          in
          return try await self.inner.fetchBackupsForResourceType(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.Backup {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func restoreBackup(
      request: RestoreBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RestoreBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreBackup(request: r, options: o)
        })
    }

    public func createBackupPlan(
      request: CreateBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupPlanRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPlan(request: r, options: o)
        })
    }

    public func updateBackupPlan(
      request: UpdateBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupPlanRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPlan(request: r, options: o)
        })
    }

    public func getBackupPlan(
      request: GetBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlan {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupPlanRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlan
          in
          return try await self.inner.getBackupPlan(request: r, options: o)
        })
    }

    public func listBackupPlans(
      request: ListBackupPlansRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlansResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupPlansRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlansResponse
          in
          return try await self.inner.listBackupPlans(request: r, options: o)
        })
    }

    public func deleteBackupPlan(
      request: DeleteBackupPlanRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupPlanRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPlan(request: r, options: o)
        })
    }

    public func getBackupPlanRevision(
      request: GetBackupPlanRevisionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanRevision {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupPlanRevisionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlanRevision
          in
          return try await self.inner.getBackupPlanRevision(request: r, options: o)
        })
    }

    public func listBackupPlanRevisions(
      request: ListBackupPlanRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupPlanRevisionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlanRevisionsResponse
          in
          return try await self.inner.listBackupPlanRevisions(request: r, options: o)
        })
    }

    public func createBackupPlanAssociation(
      request: CreateBackupPlanAssociationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackupPlanAssociationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPlanAssociation(request: r, options: o)
        })
    }

    public func updateBackupPlanAssociation(
      request: UpdateBackupPlanAssociationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackupPlanAssociationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPlanAssociation(request: r, options: o)
        })
    }

    public func getBackupPlanAssociation(
      request: GetBackupPlanAssociationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanAssociation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackupPlanAssociationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlanAssociation
          in
          return try await self.inner.getBackupPlanAssociation(request: r, options: o)
        })
    }

    public func listBackupPlanAssociations(
      request: ListBackupPlanAssociationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanAssociationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackupPlanAssociationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlanAssociationsResponse
          in
          return try await self.inner.listBackupPlanAssociations(request: r, options: o)
        })
    }

    public func fetchBackupPlanAssociationsForResourceType(
      request: FetchBackupPlanAssociationsForResourceTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupPlanAssociationsForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchBackupPlanAssociationsForResourceTypeRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudBackupDRV1.FetchBackupPlanAssociationsForResourceTypeResponse
          in
          return try await self.inner.fetchBackupPlanAssociationsForResourceType(
            request: r, options: o)
        })
    }

    public func deleteBackupPlanAssociation(
      request: DeleteBackupPlanAssociationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackupPlanAssociationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPlanAssociation(request: r, options: o)
        })
    }

    public func triggerBackup(
      request: TriggerBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: TriggerBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.triggerBackup(request: r, options: o)
        })
    }

    public func getDataSourceReference(
      request: GetDataSourceReferenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSourceReference {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDataSourceReferenceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.DataSourceReference
          in
          return try await self.inner.getDataSourceReference(request: r, options: o)
        })
    }

    public func listDataSourceReferences(
      request: ListDataSourceReferencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourceReferencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDataSourceReferencesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListDataSourceReferencesResponse
          in
          return try await self.inner.listDataSourceReferences(request: r, options: o)
        })
    }

    public func fetchDataSourceReferencesForResourceType(
      request: FetchDataSourceReferencesForResourceTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchDataSourceReferencesForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchDataSourceReferencesForResourceTypeRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudBackupDRV1.FetchDataSourceReferencesForResourceTypeResponse
          in
          return try await self.inner.fetchDataSourceReferencesForResourceType(
            request: r, options: o)
        })
    }

    public func initializeService(
      request: InitializeServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: InitializeServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.initializeService(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
