// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `BackupRule` binds the backup schedule to a retention policy.
public struct BackupRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. The unique id of this `BackupRule`. The `rule_id` is
  /// unique per `BackupPlan`.The `rule_id` must start with a lowercase letter
  /// followed by up to 62 lowercase letters, numbers, or hyphens. Pattern,
  /// /[a-z][a-z0-9-]{,62}/.
  public var ruleId: Swift.String = Swift.String()

  /// Required. Configures the duration for which backup data will be kept. It is
  /// defined in “days”. The value should be greater than or equal to minimum
  /// enforced retention of the backup vault.
  ///
  /// Minimum value is 1 and maximum value is 36159 for custom retention
  /// on-demand backup.
  /// Minimum and maximum values are workload specific for all other rules.
  public var backupRetentionDays: Swift.Int32 = Swift.Int32()

  /// The schedule that defines the automated backup workloads for this
  /// `BackupRule`.
  public var backupScheduleOneof: OneOf_BackupScheduleOneof? = nil

  /// Initialize a new instance of `BackupRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupRule().with { $0.ruleId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case ruleId = "ruleId"
    case backupRetentionDays = "backupRetentionDays"
    case standardSchedule = "standardSchedule"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.ruleId = try container.decode(Swift.String.self, forKey: .ruleId)
    self.backupRetentionDays = try container.decode(Swift.Int32.self, forKey: .backupRetentionDays)

    var backupScheduleOneof: OneOf_BackupScheduleOneof? = nil
    let backupScheduleOneofCheckAndSet = {
      if backupScheduleOneof != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'backupScheduleOneof'"))
      }
      backupScheduleOneof = $0
    }
    if let standardSchedule = try container.decodeIfPresent(
      StandardSchedule?.self, forKey: .standardSchedule)
    {
      try backupScheduleOneofCheckAndSet(.standardSchedule(standardSchedule))
    }
    self.backupScheduleOneof = backupScheduleOneof
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ruleId, forKey: .ruleId)
    try container.encode(self.backupRetentionDays, forKey: .backupRetentionDays)

    if let choice = self.backupScheduleOneof {
      switch choice {
      case .standardSchedule(let value):
        try container.encode(value, forKey: .standardSchedule)
      }
    }
  }

  /// The schedule that defines the automated backup workloads for this
  /// `BackupRule`.
  public enum OneOf_BackupScheduleOneof: Codable, Equatable, Sendable {
    /// Optional. Defines a schedule that runs within the confines of a defined
    /// window of time.
    indirect case standardSchedule(StandardSchedule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
