// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// BackupLock represents a single lock on a Backup resource.  An unexpired
/// lock on a Backup prevents the Backup from being deleted.
public struct BackupLock: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The time after which this lock is not considered valid and will
  /// no longer protect the Backup from deletion.
  public var lockUntilTime: GoogleCloudWkt.Timestamp? = nil

  /// Metadata about the owner and reason for the lock.
  public var clientLockInfo: OneOf_ClientLockInfo? = nil

  /// Initialize a new instance of `BackupLock`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupLock().with { $0.lockUntilTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case lockUntilTime = "lockUntilTime"
    case backupApplianceLockInfo = "backupApplianceLockInfo"
    case serviceLockInfo = "serviceLockInfo"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.lockUntilTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .lockUntilTime)

    var clientLockInfo: OneOf_ClientLockInfo? = nil
    let clientLockInfoCheckAndSet = {
      if clientLockInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clientLockInfo'"))
      }
      clientLockInfo = $0
    }
    if let backupApplianceLockInfo = try container.decodeIfPresent(
      BackupApplianceLockInfo?.self, forKey: .backupApplianceLockInfo)
    {
      try clientLockInfoCheckAndSet(.backupApplianceLockInfo(backupApplianceLockInfo))
    }
    if let serviceLockInfo = try container.decodeIfPresent(
      ServiceLockInfo?.self, forKey: .serviceLockInfo)
    {
      try clientLockInfoCheckAndSet(.serviceLockInfo(serviceLockInfo))
    }
    self.clientLockInfo = clientLockInfo
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.lockUntilTime, forKey: .lockUntilTime)

    if let choice = self.clientLockInfo {
      switch choice {
      case .backupApplianceLockInfo(let value):
        try container.encode(value, forKey: .backupApplianceLockInfo)
      case .serviceLockInfo(let value):
        try container.encode(value, forKey: .serviceLockInfo)
      }
    }
  }

  /// Metadata about the owner and reason for the lock.
  public enum OneOf_ClientLockInfo: Codable, Equatable, Sendable {
    /// If the client is a backup and recovery appliance, this
    /// contains metadata about why the lock exists.
    indirect case backupApplianceLockInfo(BackupApplianceLockInfo?)
    /// Output only. Contains metadata about the lock exist for Google Cloud
    /// native backups.
    indirect case serviceLockInfo(ServiceLockInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupLock"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
