// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `BackupWindow` defines a window of the day during which backup jobs will run.
public struct BackupWindow: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The hour of day (0-23) when the window starts for e.g. if value
  /// of start hour of day is 6 that mean backup window start at 6:00.
  public var startHourOfDay: Swift.Int32 = Swift.Int32()

  /// Required. The hour of day (1-24) when the window end for e.g. if value of
  /// end hour of day is 10 that mean backup window end time is 10:00.
  ///
  /// End hour of day should be greater than start hour of day.
  /// 0 <= start_hour_of_day < end_hour_of_day <= 24
  ///
  /// End hour of day is not include in backup window that mean if
  /// end_hour_of_day= 10 jobs should start before 10:00.
  public var endHourOfDay: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `BackupWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupWindow().with { $0.startHourOfDay = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupWindow"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
