// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class BackupDRLogging: BackupDRStub {
    let inner: any BackupDRStub
    let logger: Logger

    public init(_ inner: any BackupDRStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-backupdr-v1"
      logger[metadataKey: "gcp.client.service"] = "backupdr"
      logger[metadataKey: "gcp.experimental.swift.client"] = "BackupDR"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listManagementServers(
      request: ListManagementServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListManagementServersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listManagementServers",
        action: {
          (r: ListManagementServersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListManagementServersResponse
          in
          return try await self.inner.listManagementServers(request: r, options: o)
        })
    }

    public func getManagementServer(
      request: GetManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ManagementServer {
      try await self._intercept(
        request: request,
        options: options,
        name: "getManagementServer",
        action: {
          (r: GetManagementServerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ManagementServer
          in
          return try await self.inner.getManagementServer(request: r, options: o)
        })
    }

    public func createManagementServer(
      request: CreateManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createManagementServer",
        action: {
          (r: CreateManagementServerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createManagementServer(request: r, options: o)
        })
    }

    public func deleteManagementServer(
      request: DeleteManagementServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteManagementServer",
        action: {
          (r: DeleteManagementServerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteManagementServer(request: r, options: o)
        })
    }

    public func createBackupVault(
      request: CreateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackupVault",
        action: {
          (r: CreateBackupVaultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupVault(request: r, options: o)
        })
    }

    public func listBackupVaults(
      request: ListBackupVaultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupVaultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupVaults",
        action: {
          (r: ListBackupVaultsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupVaultsResponse
          in
          return try await self.inner.listBackupVaults(request: r, options: o)
        })
    }

    public func fetchUsableBackupVaults(
      request: FetchUsableBackupVaultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchUsableBackupVaultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchUsableBackupVaults",
        action: {
          (r: FetchUsableBackupVaultsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.FetchUsableBackupVaultsResponse
          in
          return try await self.inner.fetchUsableBackupVaults(request: r, options: o)
        })
    }

    public func getBackupVault(
      request: GetBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupVault {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupVault",
        action: {
          (r: GetBackupVaultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupVault
          in
          return try await self.inner.getBackupVault(request: r, options: o)
        })
    }

    public func updateBackupVault(
      request: UpdateBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackupVault",
        action: {
          (r: UpdateBackupVaultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupVault(request: r, options: o)
        })
    }

    public func deleteBackupVault(
      request: DeleteBackupVaultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackupVault",
        action: {
          (r: DeleteBackupVaultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupVault(request: r, options: o)
        })
    }

    public func listDataSources(
      request: ListDataSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDataSources",
        action: {
          (r: ListDataSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListDataSourcesResponse
          in
          return try await self.inner.listDataSources(request: r, options: o)
        })
    }

    public func getDataSource(
      request: GetDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDataSource",
        action: {
          (r: GetDataSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.DataSource
          in
          return try await self.inner.getDataSource(request: r, options: o)
        })
    }

    public func updateDataSource(
      request: UpdateDataSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDataSource",
        action: {
          (r: UpdateDataSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDataSource(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackups",
        action: {
          (r: ListBackupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func fetchBackupsForResourceType(
      request: FetchBackupsForResourceTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupsForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchBackupsForResourceType",
        action: {
          (r: FetchBackupsForResourceTypeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.FetchBackupsForResourceTypeResponse
          in
          return try await self.inner.fetchBackupsForResourceType(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.Backup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackup",
        action: {
          (r: GetBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackup",
        action: {
          (r: UpdateBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackup",
        action: {
          (r: DeleteBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func restoreBackup(
      request: RestoreBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "restoreBackup",
        action: {
          (r: RestoreBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreBackup(request: r, options: o)
        })
    }

    public func createBackupPlan(
      request: CreateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackupPlan",
        action: {
          (r: CreateBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPlan(request: r, options: o)
        })
    }

    public func updateBackupPlan(
      request: UpdateBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackupPlan",
        action: {
          (r: UpdateBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPlan(request: r, options: o)
        })
    }

    public func getBackupPlan(
      request: GetBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlan {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupPlan",
        action: {
          (r: GetBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlan
          in
          return try await self.inner.getBackupPlan(request: r, options: o)
        })
    }

    public func listBackupPlans(
      request: ListBackupPlansRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlansResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupPlans",
        action: {
          (r: ListBackupPlansRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlansResponse
          in
          return try await self.inner.listBackupPlans(request: r, options: o)
        })
    }

    public func deleteBackupPlan(
      request: DeleteBackupPlanRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackupPlan",
        action: {
          (r: DeleteBackupPlanRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPlan(request: r, options: o)
        })
    }

    public func getBackupPlanRevision(
      request: GetBackupPlanRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupPlanRevision",
        action: {
          (r: GetBackupPlanRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlanRevision
          in
          return try await self.inner.getBackupPlanRevision(request: r, options: o)
        })
    }

    public func listBackupPlanRevisions(
      request: ListBackupPlanRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupPlanRevisions",
        action: {
          (r: ListBackupPlanRevisionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlanRevisionsResponse
          in
          return try await self.inner.listBackupPlanRevisions(request: r, options: o)
        })
    }

    public func createBackupPlanAssociation(
      request: CreateBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackupPlanAssociation",
        action: {
          (r: CreateBackupPlanAssociationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackupPlanAssociation(request: r, options: o)
        })
    }

    public func updateBackupPlanAssociation(
      request: UpdateBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackupPlanAssociation",
        action: {
          (r: UpdateBackupPlanAssociationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackupPlanAssociation(request: r, options: o)
        })
    }

    public func getBackupPlanAssociation(
      request: GetBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.BackupPlanAssociation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackupPlanAssociation",
        action: {
          (r: GetBackupPlanAssociationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.BackupPlanAssociation
          in
          return try await self.inner.getBackupPlanAssociation(request: r, options: o)
        })
    }

    public func listBackupPlanAssociations(
      request: ListBackupPlanAssociationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListBackupPlanAssociationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackupPlanAssociations",
        action: {
          (r: ListBackupPlanAssociationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListBackupPlanAssociationsResponse
          in
          return try await self.inner.listBackupPlanAssociations(request: r, options: o)
        })
    }

    public func fetchBackupPlanAssociationsForResourceType(
      request: FetchBackupPlanAssociationsForResourceTypeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchBackupPlanAssociationsForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchBackupPlanAssociationsForResourceType",
        action: {
          (r: FetchBackupPlanAssociationsForResourceTypeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudBackupDRV1.FetchBackupPlanAssociationsForResourceTypeResponse
          in
          return try await self.inner.fetchBackupPlanAssociationsForResourceType(
            request: r, options: o)
        })
    }

    public func deleteBackupPlanAssociation(
      request: DeleteBackupPlanAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackupPlanAssociation",
        action: {
          (r: DeleteBackupPlanAssociationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackupPlanAssociation(request: r, options: o)
        })
    }

    public func triggerBackup(
      request: TriggerBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "triggerBackup",
        action: {
          (r: TriggerBackupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.triggerBackup(request: r, options: o)
        })
    }

    public func getDataSourceReference(
      request: GetDataSourceReferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.DataSourceReference {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDataSourceReference",
        action: {
          (r: GetDataSourceReferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.DataSourceReference
          in
          return try await self.inner.getDataSourceReference(request: r, options: o)
        })
    }

    public func listDataSourceReferences(
      request: ListDataSourceReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.ListDataSourceReferencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDataSourceReferences",
        action: {
          (r: ListDataSourceReferencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBackupDRV1.ListDataSourceReferencesResponse
          in
          return try await self.inner.listDataSourceReferences(request: r, options: o)
        })
    }

    public func fetchDataSourceReferencesForResourceType(
      request: FetchDataSourceReferencesForResourceTypeRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBackupDRV1.FetchDataSourceReferencesForResourceTypeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchDataSourceReferencesForResourceType",
        action: {
          (r: FetchDataSourceReferencesForResourceTypeRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudBackupDRV1.FetchDataSourceReferencesForResourceTypeResponse
          in
          return try await self.inner.fetchDataSourceReferencesForResourceType(
            request: r, options: o)
        })
    }

    public func initializeService(
      request: InitializeServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "initializeService",
        action: {
          (r: InitializeServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.initializeService(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
