// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// BackupApplianceBackupConfig captures the backup configuration for
/// applications that are protected by Backup Appliances.
public struct BackupApplianceBackupConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the backup appliance.
  public var backupApplianceName: Swift.String = Swift.String()

  /// The ID of the backup appliance.
  public var backupApplianceId: Swift.Int64 = Swift.Int64()

  /// The ID of the SLA of this application.
  public var slaId: Swift.Int64 = Swift.Int64()

  /// The name of the application.
  public var applicationName: Swift.String = Swift.String()

  /// The name of the host where the application is running.
  public var hostName: Swift.String = Swift.String()

  /// The name of the SLT associated with the application.
  public var sltName: Swift.String = Swift.String()

  /// The name of the SLP associated with the application.
  public var slpName: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupApplianceBackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupApplianceBackupConfig().with { $0.backupApplianceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupApplianceBackupConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
