// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A `BackupPlan` specifies some common fields, such as `description` as well
/// as one or more `BackupRule` messages. Each `BackupRule` has a retention
/// policy and defines a schedule by which the system is to perform backup
/// workloads.
public struct BackupPlan: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the `BackupPlan`.
  ///
  /// Format: `projects/{project}/locations/{location}/backupPlans/{backup_plan}`
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the `BackupPlan` resource.
  ///
  /// The description allows for additional details about `BackupPlan` and its
  /// use cases to be provided. An example description is the following:  "This
  /// is a backup plan that performs a daily backup at 6pm and retains data for 3
  /// months". The description must be at most 2048 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. This collection of key/value pairs allows for custom labels to be
  /// supplied by the user.  Example, {"tag": "Weekly"}.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. When the `BackupPlan` was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. When the `BackupPlan` was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Required. The backup rules for this `BackupPlan`. There must be at least
  /// one `BackupRule` message.
  public var backupRules: [BackupRule] = []

  /// Output only. The `State` for the `BackupPlan`.
  public var state: BackupPlan.State = BackupPlan.State()

  /// Required. The resource type to which the `BackupPlan` will be applied.
  /// Examples include, "compute.googleapis.com/Instance",
  /// "sqladmin.googleapis.com/Instance", "alloydb.googleapis.com/Cluster",
  /// "compute.googleapis.com/Disk".
  public var resourceType: Swift.String = Swift.String()

  /// Optional. `etag` is returned from the service in the response. As a user of
  /// the service, you may provide an etag value in this field to prevent stale
  /// resources.
  public var etag: Swift.String = Swift.String()

  /// Required. Resource name of backup vault which will be used as storage
  /// location for backups. Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupvault}
  public var backupVault: Swift.String = Swift.String()

  /// Output only. The Google Cloud Platform Service Account to be used by the
  /// BackupVault for taking backups. Specify the email address of the Backup
  /// Vault Service Account.
  public var backupVaultServiceAccount: Swift.String = Swift.String()

  /// Optional. Applicable only for CloudSQL and AlloyDB resource_type.
  ///
  /// Configures how long logs will be stored. It is defined in “days”. This
  /// value should be greater than or equal to minimum enforced log retention
  /// duration of the backup vault.
  public var logRetentionDays: Swift.Int64 = Swift.Int64()

  /// Output only. All resource types to which backupPlan can be applied.
  public var supportedResourceTypes: [Swift.String] = []

  /// Output only. The user friendly revision ID of the `BackupPlanRevision`.
  ///
  /// Example: v0, v1, v2, etc.
  public var revisionId: Swift.String = Swift.String()

  /// Output only. The resource id of the `BackupPlanRevision`.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/backupPlans/{backup_plan}/revisions/{revision_id}`
  public var revisionName: Swift.String = Swift.String()

  /// Initialize a new instance of `BackupPlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupPlan().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// `State` enumerates the possible states for a `BackupPlan`.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// The resource is being created.
    case creating
    /// The resource has been created and is fully usable.
    case active
    /// The resource is being deleted.
    case deleting
    /// The resource has been created but is not usable.
    case inactive
    /// The resource is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .inactive: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .inactive: return "INACTIVE"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "INACTIVE": self = .inactive
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .inactive
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .inactive: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupPlan"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
