// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// CloudSqlInstanceDataSourceProperties represents the properties of a
/// Cloud SQL resource that are stored in the DataSource.
public struct CloudSqlInstanceDataSourceProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the Cloud SQL instance backed up by the datasource.
  /// Format:
  /// projects/{project}/instances/{instance}
  public var name: Swift.String = Swift.String()

  /// Output only. The installed database version of the Cloud SQL instance.
  public var databaseInstalledVersion: Swift.String = Swift.String()

  /// Output only. The instance creation timestamp.
  public var instanceCreateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The tier (or machine type) for this instance. Example:
  /// `db-custom-1-3840`
  public var instanceTier: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudSqlInstanceDataSourceProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSqlInstanceDataSourceProperties().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.CloudSqlInstanceDataSourceProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
