// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// CloudSqlInstanceBackupProperties represents Cloud SQL Instance
/// Backup properties.
public struct CloudSqlInstanceBackupProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The installed database version of the Cloud SQL instance
  /// when the backup was taken.
  public var databaseInstalledVersion: Swift.String = Swift.String()

  /// Output only. Whether the backup is a final backup.
  public var finalBackup: Swift.Bool = Swift.Bool()

  /// Output only. The source instance of the backup.
  /// Format:
  /// projects/{project}/instances/{instance}
  public var sourceInstance: Swift.String = Swift.String()

  /// Output only. The instance creation timestamp.
  public var instanceCreateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The tier (or machine type) for this instance. Example:
  /// `db-custom-1-3840`
  public var instanceTier: Swift.String = Swift.String()

  /// Output only. The instance delete timestamp.
  public var instanceDeleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `CloudSqlInstanceBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSqlInstanceBackupProperties().with { $0.databaseInstalledVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.CloudSqlInstanceBackupProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
