// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ComputeInstanceRestoreProperties represents Compute Engine instance
/// properties to be overridden during restore.
public struct ComputeInstanceRestoreProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the compute instance.
  public var name: Swift.String? = nil

  /// Optional. Controls for advanced machine-related behavior features.
  public var advancedMachineFeatures: AdvancedMachineFeatures? = nil

  /// Optional. Allows this instance to send and receive packets with
  /// non-matching destination or source IPs.
  public var canIpForward: Swift.Bool? = nil

  /// Optional. Controls Confidential compute options on the instance
  public var confidentialInstanceConfig: ConfidentialInstanceConfig? = nil

  /// Optional. Whether the resource should be protected against deletion.
  public var deletionProtection: Swift.Bool? = nil

  /// Optional. An optional description of this resource. Provide this property
  /// when you create the resource.
  public var description: Swift.String? = nil

  /// Optional. Array of disks associated with this instance. Persistent disks
  /// must be created before you can assign them. Source regional persistent
  /// disks will be restored with default replica zones if not specified.
  public var disks: [AttachedDisk] = []

  /// Optional. Enables display device for the instance.
  public var displayDevice: DisplayDevice? = nil

  /// Optional. A list of the type and count of accelerator cards attached to the
  /// instance.
  public var guestAccelerators: [AcceleratorConfig] = []

  /// Optional. Specifies the hostname of the instance. The specified hostname
  /// must be RFC1035 compliant. If hostname is not specified, the default
  /// hostname is [INSTANCE_NAME].c.[PROJECT_ID].internal when using the global
  /// DNS, and [INSTANCE_NAME].[ZONE].c.[PROJECT_ID].internal when using zonal
  /// DNS.
  public var hostname: Swift.String? = nil

  /// Optional. Encrypts suspended data for an instance with a
  /// customer-managed encryption key.
  public var instanceEncryptionKey: CustomerEncryptionKey? = nil

  /// Optional. KeyRevocationActionType of the instance.
  public var keyRevocationActionType: KeyRevocationActionType? = nil

  /// Optional. Labels to apply to this instance.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Full or partial URL of the machine type resource to use for this
  /// instance.
  public var machineType: Swift.String? = nil

  /// Optional. This includes custom metadata and predefined keys.
  public var metadata: Metadata? = nil

  /// Optional. Minimum CPU platform to use for this instance.
  public var minCpuPlatform: Swift.String? = nil

  /// Optional. An array of network configurations for this instance. These
  /// specify how interfaces are configured to interact with other network
  /// services, such as connecting to the internet. Multiple interfaces are
  /// supported per instance. Required to restore in different project or region.
  public var networkInterfaces: [NetworkInterface] = []

  /// Optional. Configure network performance such as egress bandwidth tier.
  public var networkPerformanceConfig: NetworkPerformanceConfig? = nil

  /// Input only. Additional params passed with the request, but not persisted
  /// as part of resource payload.
  public var params: InstanceParams? = nil

  /// Optional. The private IPv6 google access type for the VM.
  /// If not specified, use INHERIT_FROM_SUBNETWORK as default.
  public var privateIpv6GoogleAccess:
    ComputeInstanceRestoreProperties.InstancePrivateIpv6GoogleAccess? = nil

  /// Optional. Specifies the reservations that this instance can consume from.
  public var allocationAffinity: AllocationAffinity? = nil

  /// Optional. Resource policies applied to this instance.
  /// By default, no resource policies will be applied.
  public var resourcePolicies: [Swift.String] = []

  /// Optional. Sets the scheduling options for this instance.
  public var scheduling: Scheduling? = nil

  /// Optional. A list of service accounts, with their specified scopes,
  /// authorized for this instance. Only one service account per VM instance is
  /// supported.
  public var serviceAccounts: [ServiceAccount] = []

  /// Optional. Tags to apply to this instance. Tags are used to identify valid
  /// sources or targets for network firewalls and are specified by the client
  /// during instance creation.
  public var tags: Tags? = nil

  /// Initialize a new instance of `ComputeInstanceRestoreProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceRestoreProperties().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case advancedMachineFeatures = "advancedMachineFeatures"
    case canIpForward = "canIpForward"
    case confidentialInstanceConfig = "confidentialInstanceConfig"
    case deletionProtection = "deletionProtection"
    case description = "description"
    case disks = "disks"
    case displayDevice = "displayDevice"
    case guestAccelerators = "guestAccelerators"
    case hostname = "hostname"
    case instanceEncryptionKey = "instanceEncryptionKey"
    case keyRevocationActionType = "keyRevocationActionType"
    case labels = "labels"
    case machineType = "machineType"
    case metadata = "metadata"
    case minCpuPlatform = "minCpuPlatform"
    case networkInterfaces = "networkInterfaces"
    case networkPerformanceConfig = "networkPerformanceConfig"
    case params = "params"
    case privateIpv6GoogleAccess = "privateIpv6GoogleAccess"
    case allocationAffinity = "reservationAffinity"
    case resourcePolicies = "resourcePolicies"
    case scheduling = "scheduling"
    case serviceAccounts = "serviceAccounts"
    case tags = "tags"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
    self.advancedMachineFeatures = try container.decodeIfPresent(
      AdvancedMachineFeatures.self, forKey: .advancedMachineFeatures)
    self.canIpForward = try container.decodeIfPresent(Swift.Bool.self, forKey: .canIpForward)
    self.confidentialInstanceConfig = try container.decodeIfPresent(
      ConfidentialInstanceConfig.self, forKey: .confidentialInstanceConfig)
    self.deletionProtection = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deletionProtection)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    self.disks = try container.decode([AttachedDisk].self, forKey: .disks)
    self.displayDevice = try container.decodeIfPresent(DisplayDevice.self, forKey: .displayDevice)
    self.guestAccelerators = try container.decode(
      [AcceleratorConfig].self, forKey: .guestAccelerators)
    self.hostname = try container.decodeIfPresent(Swift.String.self, forKey: .hostname)
    self.instanceEncryptionKey = try container.decodeIfPresent(
      CustomerEncryptionKey.self, forKey: .instanceEncryptionKey)
    self.keyRevocationActionType = try container.decodeIfPresent(
      KeyRevocationActionType.self, forKey: .keyRevocationActionType)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.machineType = try container.decodeIfPresent(Swift.String.self, forKey: .machineType)
    self.metadata = try container.decodeIfPresent(Metadata.self, forKey: .metadata)
    self.minCpuPlatform = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform)
    self.networkInterfaces = try container.decode(
      [NetworkInterface].self, forKey: .networkInterfaces)
    self.networkPerformanceConfig = try container.decodeIfPresent(
      NetworkPerformanceConfig.self, forKey: .networkPerformanceConfig)
    self.params = try container.decodeIfPresent(InstanceParams.self, forKey: .params)
    self.privateIpv6GoogleAccess = try container.decodeIfPresent(
      ComputeInstanceRestoreProperties.InstancePrivateIpv6GoogleAccess.self,
      forKey: .privateIpv6GoogleAccess)
    self.allocationAffinity = try container.decodeIfPresent(
      AllocationAffinity.self, forKey: .allocationAffinity)
    self.resourcePolicies = try container.decode([Swift.String].self, forKey: .resourcePolicies)
    self.scheduling = try container.decodeIfPresent(Scheduling.self, forKey: .scheduling)
    self.serviceAccounts = try container.decode([ServiceAccount].self, forKey: .serviceAccounts)
    self.tags = try container.decodeIfPresent(Tags.self, forKey: .tags)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.advancedMachineFeatures, forKey: .advancedMachineFeatures)
    try container.encode(self.canIpForward, forKey: .canIpForward)
    try container.encode(self.confidentialInstanceConfig, forKey: .confidentialInstanceConfig)
    try container.encode(self.deletionProtection, forKey: .deletionProtection)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.disks, forKey: .disks)
    try container.encode(self.displayDevice, forKey: .displayDevice)
    try container.encode(self.guestAccelerators, forKey: .guestAccelerators)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.instanceEncryptionKey, forKey: .instanceEncryptionKey)
    try container.encode(self.keyRevocationActionType, forKey: .keyRevocationActionType)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.metadata, forKey: .metadata)
    try container.encode(self.minCpuPlatform, forKey: .minCpuPlatform)
    try container.encode(self.networkInterfaces, forKey: .networkInterfaces)
    try container.encode(self.networkPerformanceConfig, forKey: .networkPerformanceConfig)
    try container.encode(self.params, forKey: .params)
    try container.encode(self.privateIpv6GoogleAccess, forKey: .privateIpv6GoogleAccess)
    try container.encode(self.allocationAffinity, forKey: .allocationAffinity)
    try container.encode(self.resourcePolicies, forKey: .resourcePolicies)
    try container.encode(self.scheduling, forKey: .scheduling)
    try container.encode(self.serviceAccounts, forKey: .serviceAccounts)
    try container.encode(self.tags, forKey: .tags)
  }

  /// The private IPv6 google access type for the VMs.
  public enum InstancePrivateIpv6GoogleAccess: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Each network interface inherits PrivateIpv6GoogleAccess from its
    /// subnetwork.
    case inheritFromSubnetwork
    /// Outbound private IPv6 access from VMs in this subnet to Google services.
    /// If specified, the subnetwork who is attached to the instance's default
    /// network interface will be assigned an internal IPv6 prefix if it doesn't
    /// have before.
    case enableOutboundVmAccessToGoogle
    /// Bidirectional private IPv6 access to/from Google services. If
    /// specified, the subnetwork who is attached to the instance's default
    /// network interface will be assigned an internal IPv6 prefix if it doesn't
    /// have before.
    case enableBidirectionalAccessToGoogle
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inheritFromSubnetwork: return 1
      case .enableOutboundVmAccessToGoogle: return 2
      case .enableBidirectionalAccessToGoogle: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED"
      case .inheritFromSubnetwork: return "INHERIT_FROM_SUBNETWORK"
      case .enableOutboundVmAccessToGoogle: return "ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE"
      case .enableBidirectionalAccessToGoogle: return "ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstancePrivateIpv6GoogleAccess/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED": self = .unspecified
      case "INHERIT_FROM_SUBNETWORK": self = .inheritFromSubnetwork
      case "ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE": self = .enableOutboundVmAccessToGoogle
      case "ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE": self = .enableBidirectionalAccessToGoogle
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstancePrivateIpv6GoogleAccess/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inheritFromSubnetwork
      case 2: self = .enableOutboundVmAccessToGoogle
      case 3: self = .enableBidirectionalAccessToGoogle
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inheritFromSubnetwork: return try container.encode(1)
      case .enableOutboundVmAccessToGoogle: return try container.encode(2)
      case .enableBidirectionalAccessToGoogle: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ComputeInstanceRestoreProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
