// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ComputeInstanceBackupProperties represents Compute Engine instance backup
/// properties.
public struct ComputeInstanceBackupProperties: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// An optional text description for the instances that are created from these
  /// properties.
  public var description: Swift.String? = nil

  /// A list of tags to apply to the instances that are created from these
  /// properties. The tags identify valid sources or targets for network
  /// firewalls. The setTags method can modify this list of tags. Each tag within
  /// the list must comply with RFC1035 (https://www.ietf.org/rfc/rfc1035.txt).
  public var tags: Tags? = nil

  /// The machine type to use for instances that are created from these
  /// properties.
  public var machineType: Swift.String? = nil

  /// Enables instances created based on these properties to send packets with
  /// source IP addresses other than their own and receive packets with
  /// destination IP addresses other than their own. If these instances will be
  /// used as an IP gateway or it will be set as the next-hop in a Route
  /// resource, specify `true`. If unsure, leave this set to `false`. See the
  /// https://cloud.google.com/vpc/docs/using-routes#canipforward
  /// documentation for more information.
  public var canIpForward: Swift.Bool? = nil

  /// An array of network access configurations for this interface.
  public var networkInterface: [NetworkInterface] = []

  /// An array of disks that are associated with the instances that are created
  /// from these properties.
  public var disk: [AttachedDisk] = []

  /// The metadata key/value pairs to assign to instances that are created from
  /// these properties. These pairs can consist of custom metadata or predefined
  /// keys. See https://cloud.google.com/compute/docs/metadata/overview for more
  /// information.
  public var metadata: Metadata? = nil

  /// A list of service accounts with specified scopes. Access tokens for these
  /// service accounts are available to the instances that are created from
  /// these properties. Use metadata queries to obtain the access tokens for
  /// these instances.
  public var serviceAccount: [ServiceAccount] = []

  /// Specifies the scheduling options for the instances that are created from
  /// these properties.
  public var scheduling: Scheduling? = nil

  /// A list of guest accelerator cards' type and count to use for instances
  /// created from these properties.
  public var guestAccelerator: [AcceleratorConfig] = []

  /// Minimum cpu/platform to be used by instances. The instance may be
  /// scheduled on the specified or newer cpu/platform. Applicable values are the
  /// friendly names of CPU platforms, such as
  /// `minCpuPlatform: Intel Haswell` or `minCpuPlatform: Intel Sandy Bridge`.
  /// For more information, read
  /// https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform.
  public var minCpuPlatform: Swift.String? = nil

  /// KeyRevocationActionType of the instance. Supported options are "STOP" and
  /// "NONE". The default value is "NONE" if it is not specified.
  public var keyRevocationActionType: KeyRevocationActionType? = nil

  /// The source instance used to create this backup. This can be a partial or
  /// full URL to the resource. For example, the following are valid values:
  ///   -https://www.googleapis.com/compute/v1/projects/project/zones/zone/instances/instance
  ///   -projects/project/zones/zone/instances/instance
  public var sourceInstance: Swift.String? = nil

  /// Labels to apply to instances that are created from these properties.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `ComputeInstanceBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceBackupProperties().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ComputeInstanceBackupProperties"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
