// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// ComputeInstanceDataSourceProperties represents the properties of a
/// ComputeEngine resource that are stored in the DataSource.
public struct ComputeInstanceDataSourceProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the compute instance backed up by the datasource.
  public var name: Swift.String = Swift.String()

  /// The description of the Compute Engine instance.
  public var description: Swift.String = Swift.String()

  /// The machine type of the instance.
  public var machineType: Swift.String = Swift.String()

  /// The total number of disks attached to the Instance.
  public var totalDiskCount: Swift.Int64 = Swift.Int64()

  /// The sum of all the disk sizes.
  public var totalDiskSizeGb: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `ComputeInstanceDataSourceProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceDataSourceProperties().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ComputeInstanceDataSourceProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
