// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DataSourceGcpResource is used for protected resources that are Google Cloud
/// Resources. This name is easeier to understand than GcpResourceDataSource or
/// GcpDataSourceResource
public struct DataSourceGcpResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Full resource pathname URL of the source Google Cloud
  /// resource.
  public var gcpResourcename: Swift.String = Swift.String()

  /// Location of the resource: <region>/<zone>/"global"/"unspecified".
  public var location: Swift.String = Swift.String()

  /// The type of the Google Cloud resource. Use the Unified Resource Type,
  /// eg. compute.googleapis.com/Instance.
  public var type: Swift.String = Swift.String()

  /// gcp_Properties has properties of the Google Cloud Resource.
  public var gcpResourceProperties: OneOf_GcpResourceProperties? = nil

  /// Initialize a new instance of `DataSourceGcpResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceGcpResource().with { $0.gcpResourcename = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcpResourcename = "gcpResourcename"
    case location = "location"
    case type = "type"
    case computeInstanceDatasourceProperties = "computeInstanceDatasourceProperties"
    case cloudSqlInstanceDatasourceProperties = "cloudSqlInstanceDatasourceProperties"
    case alloyDbClusterDatasourceProperties = "alloyDbClusterDatasourceProperties"
    case diskDatasourceProperties = "diskDatasourceProperties"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.gcpResourcename = try container.decode(Swift.String.self, forKey: .gcpResourcename)
    self.location = try container.decode(Swift.String.self, forKey: .location)
    self.type = try container.decode(Swift.String.self, forKey: .type)

    var gcpResourceProperties: OneOf_GcpResourceProperties? = nil
    let gcpResourcePropertiesCheckAndSet = {
      if gcpResourceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'gcpResourceProperties'"))
      }
      gcpResourceProperties = $0
    }
    if let computeInstanceDatasourceProperties = try container.decodeIfPresent(
      ComputeInstanceDataSourceProperties?.self, forKey: .computeInstanceDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .computeInstanceDatasourceProperties(computeInstanceDatasourceProperties))
    }
    if let cloudSqlInstanceDatasourceProperties = try container.decodeIfPresent(
      CloudSqlInstanceDataSourceProperties?.self, forKey: .cloudSqlInstanceDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .cloudSqlInstanceDatasourceProperties(cloudSqlInstanceDatasourceProperties))
    }
    if let alloyDbClusterDatasourceProperties = try container.decodeIfPresent(
      AlloyDBClusterDataSourceProperties?.self, forKey: .alloyDbClusterDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .alloyDbClusterDatasourceProperties(alloyDbClusterDatasourceProperties))
    }
    if let diskDatasourceProperties = try container.decodeIfPresent(
      DiskDataSourceProperties?.self, forKey: .diskDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(.diskDatasourceProperties(diskDatasourceProperties))
    }
    self.gcpResourceProperties = gcpResourceProperties
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcpResourcename, forKey: .gcpResourcename)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.type, forKey: .type)

    if let choice = self.gcpResourceProperties {
      switch choice {
      case .computeInstanceDatasourceProperties(let value):
        try container.encode(value, forKey: .computeInstanceDatasourceProperties)
      case .cloudSqlInstanceDatasourceProperties(let value):
        try container.encode(value, forKey: .cloudSqlInstanceDatasourceProperties)
      case .alloyDbClusterDatasourceProperties(let value):
        try container.encode(value, forKey: .alloyDbClusterDatasourceProperties)
      case .diskDatasourceProperties(let value):
        try container.encode(value, forKey: .diskDatasourceProperties)
      }
    }
  }

  /// gcp_Properties has properties of the Google Cloud Resource.
  public enum OneOf_GcpResourceProperties: Codable, Equatable, Sendable {
    /// ComputeInstanceDataSourceProperties has a subset of Compute Instance
    /// properties that are useful at the Datasource level.
    indirect case computeInstanceDatasourceProperties(ComputeInstanceDataSourceProperties?)
    /// Output only. CloudSqlInstanceDataSourceProperties has a subset of Cloud
    /// SQL Instance properties that are useful at the Datasource level.
    indirect case cloudSqlInstanceDatasourceProperties(CloudSqlInstanceDataSourceProperties?)
    /// Output only. AlloyDBClusterDataSourceProperties has a subset of AlloyDB
    /// cluster properties that are useful at the Datasource level.
    indirect case alloyDbClusterDatasourceProperties(AlloyDBClusterDataSourceProperties?)
    /// DiskDataSourceProperties has a subset of Disk properties that are useful
    /// at the Datasource level.
    indirect case diskDatasourceProperties(DiskDataSourceProperties?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
