// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing a DataSource object.
/// Datasource object used to represent Datasource details for both admin and
/// basic view.
public struct DataSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the datasource to create.
  /// It must have the
  /// format`"projects/{project}/locations/{location}/backupVaults/{backupvault}/dataSources/{datasource}"`.
  /// `{datasource}` cannot be changed after creation. It must be between 3-63
  /// characters long and must be unique within the backup vault.
  public var name: Swift.String = Swift.String()

  /// Output only. The DataSource resource instance state.
  public var state: DataSource.State = DataSource.State()

  /// Optional. Resource labels to represent user provided metadata.
  /// No labels currently defined:
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the instance was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the instance was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Number of backups in the data source.
  public var backupCount: Swift.Int64? = nil

  /// Server specified ETag for the ManagementServer resource to prevent
  /// simultaneous updates from overwiting each other.
  public var etag: Swift.String? = nil

  /// The number of bytes (metadata and data) stored in this datasource.
  public var totalStoredBytes: Swift.Int64? = nil

  /// Output only. The backup configuration state.
  public var configState: BackupConfigState = BackupConfigState()

  /// Output only. Details of how the resource is configured for backup.
  public var backupConfigInfo: BackupConfigInfo? = nil

  /// Output only. This field is set to true if the backup is blocked by vault
  /// access restriction.
  public var backupBlockedByVaultAccessRestriction: Swift.Bool = Swift.Bool()

  /// The source resource that is represented by this DataSource. It can be a
  /// Google Cloud resource, or one backed up by a Backup Appliance.
  public var sourceResource: OneOf_SourceResource? = nil

  /// Initialize a new instance of `DataSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case state = "state"
    case labels = "labels"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case backupCount = "backupCount"
    case etag = "etag"
    case totalStoredBytes = "totalStoredBytes"
    case configState = "configState"
    case backupConfigInfo = "backupConfigInfo"
    case dataSourceGcpResource = "dataSourceGcpResource"
    case dataSourceBackupApplianceApplication = "dataSourceBackupApplianceApplication"
    case backupBlockedByVaultAccessRestriction = "backupBlockedByVaultAccessRestriction"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.state = try container.decode(DataSource.State.self, forKey: .state)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.backupCount = try container.decodeIfPresent(Swift.Int64.self, forKey: .backupCount)
    self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
    self.totalStoredBytes = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .totalStoredBytes)
    self.configState = try container.decode(BackupConfigState.self, forKey: .configState)
    self.backupConfigInfo = try container.decodeIfPresent(
      BackupConfigInfo.self, forKey: .backupConfigInfo)
    self.backupBlockedByVaultAccessRestriction = try container.decode(
      Swift.Bool.self, forKey: .backupBlockedByVaultAccessRestriction)

    var sourceResource: OneOf_SourceResource? = nil
    let sourceResourceCheckAndSet = {
      if sourceResource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceResource'"))
      }
      sourceResource = $0
    }
    if let dataSourceGcpResource = try container.decodeIfPresent(
      DataSourceGcpResource?.self, forKey: .dataSourceGcpResource)
    {
      try sourceResourceCheckAndSet(.dataSourceGcpResource(dataSourceGcpResource))
    }
    if let dataSourceBackupApplianceApplication = try container.decodeIfPresent(
      DataSourceBackupApplianceApplication?.self, forKey: .dataSourceBackupApplianceApplication)
    {
      try sourceResourceCheckAndSet(
        .dataSourceBackupApplianceApplication(dataSourceBackupApplianceApplication))
    }
    self.sourceResource = sourceResource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.backupCount, forKey: .backupCount)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.totalStoredBytes, forKey: .totalStoredBytes)
    try container.encode(self.configState, forKey: .configState)
    try container.encode(self.backupConfigInfo, forKey: .backupConfigInfo)
    try container.encode(
      self.backupBlockedByVaultAccessRestriction, forKey: .backupBlockedByVaultAccessRestriction)

    if let choice = self.sourceResource {
      switch choice {
      case .dataSourceGcpResource(let value):
        try container.encode(value, forKey: .dataSourceGcpResource)
      case .dataSourceBackupApplianceApplication(let value):
        try container.encode(value, forKey: .dataSourceBackupApplianceApplication)
      }
    }
  }

  /// Holds the state of the data source resource.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// The data source is being created.
    case creating
    /// The data source has been created and is fully usable.
    case active
    /// The data source is being deleted.
    case deleting
    /// The data source is experiencing an issue and might be unusable.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .error: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source resource that is represented by this DataSource. It can be a
  /// Google Cloud resource, or one backed up by a Backup Appliance.
  public enum OneOf_SourceResource: Codable, Equatable, Sendable {
    /// The backed up resource is a Google Cloud resource.
    /// The word 'DataSource' was included in the names to indicate that this is
    /// the representation of the Google Cloud resource used within the
    /// DataSource object.
    indirect case dataSourceGcpResource(DataSourceGcpResource?)
    /// The backed up resource is a backup appliance application.
    indirect case dataSourceBackupApplianceApplication(DataSourceBackupApplianceApplication?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
