// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The GCP resource that the DataSource is associated with.
public struct DataSourceGcpResourceInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the GCP resource.
  /// Ex: projects/{project}/zones/{zone}/instances/{instance}
  public var gcpResourcename: Swift.String = Swift.String()

  /// Output only. The type of the GCP resource.
  /// Ex: compute.googleapis.com/Instance
  public var type: Swift.String = Swift.String()

  /// Output only. The location of the GCP resource.
  /// Ex: <region>/<zone>/"global"/"unspecified"
  public var location: Swift.String = Swift.String()

  /// The properties of the GCP resource.
  public var resourceProperties: OneOf_ResourceProperties? = nil

  /// Initialize a new instance of `DataSourceGcpResourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceGcpResourceInfo().with { $0.gcpResourcename = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcpResourcename = "gcpResourcename"
    case type = "type"
    case location = "location"
    case cloudSqlInstanceProperties = "cloudSqlInstanceProperties"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.gcpResourcename = try container.decode(Swift.String.self, forKey: .gcpResourcename)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.location = try container.decode(Swift.String.self, forKey: .location)

    var resourceProperties: OneOf_ResourceProperties? = nil
    let resourcePropertiesCheckAndSet = {
      if resourceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceProperties'"))
      }
      resourceProperties = $0
    }
    if let cloudSqlInstanceProperties = try container.decodeIfPresent(
      CloudSqlInstanceDataSourceReferenceProperties?.self, forKey: .cloudSqlInstanceProperties)
    {
      try resourcePropertiesCheckAndSet(.cloudSqlInstanceProperties(cloudSqlInstanceProperties))
    }
    self.resourceProperties = resourceProperties
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcpResourcename, forKey: .gcpResourcename)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.location, forKey: .location)

    if let choice = self.resourceProperties {
      switch choice {
      case .cloudSqlInstanceProperties(let value):
        try container.encode(value, forKey: .cloudSqlInstanceProperties)
      }
    }
  }

  /// The properties of the GCP resource.
  public enum OneOf_ResourceProperties: Codable, Equatable, Sendable {
    /// Output only. The properties of the Cloud SQL instance.
    indirect case cloudSqlInstanceProperties(CloudSqlInstanceDataSourceReferenceProperties?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResourceInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
