// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BackupApplianceApplication describes a Source Resource when it is an
/// application backed up by a BackupAppliance.
public struct DataSourceBackupApplianceApplication: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the Application as known to the Backup Appliance.
  public var applicationName: Swift.String = Swift.String()

  /// Appliance name.
  public var backupAppliance: Swift.String = Swift.String()

  /// Appliance Id of the Backup Appliance.
  public var applianceId: Swift.Int64 = Swift.Int64()

  /// The type of the application. e.g. VMBackup
  public var type: Swift.String = Swift.String()

  /// The appid field of the application within the Backup Appliance.
  public var applicationId: Swift.Int64 = Swift.Int64()

  /// Hostname of the host where the application is running.
  public var hostname: Swift.String = Swift.String()

  /// Hostid of the application host.
  public var hostId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `DataSourceBackupApplianceApplication`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceBackupApplianceApplication().with { $0.applicationName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceBackupApplianceApplication"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
