// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DataSourceReference is a reference to a DataSource resource.
public struct DataSourceReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the DataSourceReference.
  /// Format:
  /// projects/{project}/locations/{location}/dataSourceReferences/{data_source_reference}
  public var name: Swift.String = Swift.String()

  /// Output only. The resource name of the DataSource.
  /// Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupVault}/dataSources/{dataSource}
  public var dataSource: Swift.String = Swift.String()

  /// Output only. The time when the DataSourceReference was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The backup configuration state of the DataSource.
  public var dataSourceBackupConfigState: BackupConfigState = BackupConfigState()

  /// Output only. Number of backups in the DataSource.
  public var dataSourceBackupCount: Swift.Int64 = Swift.Int64()

  /// Output only. Information of backup configuration on the DataSource.
  public var dataSourceBackupConfigInfo: DataSourceBackupConfigInfo? = nil

  /// Output only. The GCP resource that the DataSource is associated with.
  public var dataSourceGcpResourceInfo: DataSourceGcpResourceInfo? = nil

  /// Output only. Total size of the storage used by all backup resources for the
  /// referenced datasource.
  public var totalStoredBytes: Swift.Int64? = nil

  /// Initialize a new instance of `DataSourceReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceReference().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceReference"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
