// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for deleting a BackupVault.
public struct DeleteBackupVaultRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the resource.
  public var name: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set to true, any data source from this backup vault will also
  /// be deleted.
  public var force: Swift.Bool = Swift.Bool()

  /// The current etag of the backup vault.
  /// If an etag is provided and does not match the current etag of the
  /// connection, deletion will be blocked.
  public var etag: Swift.String = Swift.String()

  /// Optional. Only validate the request, but do not perform mutations.
  /// The default is 'false'.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If true and the BackupVault is not found, the request will
  /// succeed but no action will be taken.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. If set to true, backupvault deletion will proceed even if there
  /// are backup plans referencing the backupvault. The default is 'false'.
  public var ignoreBackupPlanReferences: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteBackupVaultRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteBackupVaultRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DeleteBackupVaultRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
