// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DiskRestoreProperties represents the properties of a Disk restore.
public struct DiskRestoreProperties: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the disk.
  public var name: Swift.String? = nil

  /// Optional. An optional description of this resource. Provide this property
  /// when you create the resource.
  public var description: Swift.String? = nil

  /// Required. The size of the disk in GB.
  public var sizeGb: Swift.Int64? = nil

  /// Optional. A list of publicly available licenses that are applicable to this
  /// backup. This is applicable if the original image had licenses attached,
  /// e.g. Windows image
  public var licenses: [Swift.String] = []

  /// Optional. A list of features to enable in the guest operating system. This
  /// is applicable only for bootable images.
  public var guestOsFeature: [GuestOsFeature] = []

  /// Optional. Encrypts the disk using a
  /// customer-supplied encryption key or a customer-managed encryption key.
  public var diskEncryptionKey: CustomerEncryptionKey? = nil

  /// Optional. Physical block size of the persistent disk, in bytes.
  /// If not present in a request, a default value is used.
  /// Currently, the supported size is 4096.
  public var physicalBlockSizeBytes: Swift.Int64? = nil

  /// Optional. Indicates how many IOPS to provision for the disk. This sets the
  /// number of I/O operations per second that the disk can handle.
  public var provisionedIops: Swift.Int64? = nil

  /// Optional. Indicates how much throughput to provision for the disk. This
  /// sets the number of throughput MB per second that the disk can handle.
  public var provisionedThroughput: Swift.Int64? = nil

  /// Optional. Indicates whether this disk is using confidential compute mode.
  /// Encryption with a Cloud KMS key is required to enable this option.
  public var enableConfidentialCompute: Swift.Bool? = nil

  /// Optional. The storage pool in which the new disk is created. You can
  /// provide this as a partial or full URL to the resource.
  public var storagePool: Swift.String? = nil

  /// Optional. The access mode of the disk.
  public var accessMode: DiskRestoreProperties.AccessMode? = nil

  /// Optional. The architecture of the source disk. Valid values are
  /// ARM64 or X86_64.
  public var architecture: DiskRestoreProperties.Architecture? = nil

  /// Optional. Resource policies applied to this disk.
  public var resourcePolicy: [Swift.String] = []

  /// Required. URL of the disk type resource describing which disk type to use
  /// to create the disk.
  public var type: Swift.String? = nil

  /// Optional. Labels to apply to this disk. These can be modified later using
  /// <code>setLabels</code> method. Label values can be empty.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Resource manager tags to be bound to the disk.
  public var resourceManagerTags: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `DiskRestoreProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskRestoreProperties().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The supported access modes of the disk.
  public enum AccessMode: Codable, Equatable, Sendable {
    /// The default AccessMode, means the disk can be attached to single instance
    /// in RW mode.
    case readWriteSingle
    /// The AccessMode means the disk can be attached to multiple instances in RW
    /// mode.
    case readWriteMany
    /// The AccessMode means the disk can be attached to multiple instances in RO
    /// mode.
    case readOnlyMany
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .readWriteSingle
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .readWriteSingle: return 0
      case .readWriteMany: return 1
      case .readOnlyMany: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .readWriteSingle: return "READ_WRITE_SINGLE"
      case .readWriteMany: return "READ_WRITE_MANY"
      case .readOnlyMany: return "READ_ONLY_MANY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccessMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "READ_WRITE_SINGLE": self = .readWriteSingle
      case "READ_WRITE_MANY": self = .readWriteMany
      case "READ_ONLY_MANY": self = .readOnlyMany
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccessMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .readWriteSingle
      case 1: self = .readWriteMany
      case 2: self = .readOnlyMany
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .readWriteSingle: return try container.encode(0)
      case .readWriteMany: return try container.encode(1)
      case .readOnlyMany: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Architecture of the source disk.
  public enum Architecture: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Disks with architecture X86_64
    case x8664
    /// Disks with architecture ARM64
    case arm64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .x8664: return 1
      case .arm64: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ARCHITECTURE_UNSPECIFIED"
      case .x8664: return "X86_64"
      case .arm64: return "ARM64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Architecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "X86_64": self = .x8664
      case "ARM64": self = .arm64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Architecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .x8664
      case 2: self = .arm64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .x8664: return try container.encode(1)
      case .arm64: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DiskRestoreProperties"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
