// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for the FetchBackupsForResourceType method.
public struct FetchBackupsForResourceTypeRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Datasources are the parent resource for the backups.
  /// Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupVaultId}/dataSources/{datasourceId}
  public var parent: Swift.String = Swift.String()

  /// Required. The type of the GCP resource.
  /// Ex: sqladmin.googleapis.com/Instance
  public var resourceType: Swift.String = Swift.String()

  /// Optional. The maximum number of Backups to return. The service may
  /// return fewer than this value. If unspecified, at most 50
  /// Backups will be returned. The maximum value is 100; values
  /// above 100 will be coerced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous call of
  /// `FetchBackupsForResourceType`.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `FetchBackupsForResourceType` must match
  /// the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters the results fetched in the
  /// response. The expression must specify the field name, a comparison
  /// operator, and the value that you want to use for filtering. Supported
  /// fields:
  public var filter: Swift.String = Swift.String()

  /// Optional. A comma-separated list of fields to order by, sorted in ascending
  /// order. Use "desc" after a field name for descending.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. This parameter is used to specify the view of the backup.
  /// If not specified, the default view is BASIC.
  public var view: BackupView = BackupView()

  /// Initialize a new instance of `FetchBackupsForResourceTypeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchBackupsForResourceTypeRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.FetchBackupsForResourceTypeRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
