// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GcpBackupConfig captures the Backup configuration details for Google Cloud
/// resources. All Google Cloud resources regardless of type are protected with
/// backup plan associations.
public struct GcpBackupConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the backup plan.
  public var backupPlan: Swift.String = Swift.String()

  /// The description of the backup plan.
  public var backupPlanDescription: Swift.String = Swift.String()

  /// The name of the backup plan association.
  public var backupPlanAssociation: Swift.String = Swift.String()

  /// The names of the backup plan rules which point to this backupvault
  public var backupPlanRules: [Swift.String] = []

  /// The name of the backup plan revision.
  public var backupPlanRevisionName: Swift.String = Swift.String()

  /// The user friendly id of the backup plan revision.
  /// E.g. v0, v1 etc.
  public var backupPlanRevisionId: Swift.String = Swift.String()

  /// Initialize a new instance of `GcpBackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcpBackupConfig().with { $0.backupPlan = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.GcpBackupConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
