// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ManagementServer describes a single BackupDR ManagementServer instance.
public struct ManagementServer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name.
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the ManagementServer instance (2048 characters
  /// or less).
  public var description: Swift.String = Swift.String()

  /// Optional. Resource labels to represent user provided metadata.
  /// Labels currently defined:
  /// 1. migrate_from_go=<false|true>
  ///    If set to true, the MS is created in migration ready mode.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the instance was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The type of the ManagementServer resource.
  public var type: ManagementServer.InstanceType = ManagementServer.InstanceType()

  /// Output only. The hostname or ip address of the exposed AGM endpoints, used
  /// by clients to connect to AGM/RD graphical user interface and APIs.
  public var managementUri: ManagementURI? = nil

  /// Output only. The hostnames of the exposed AGM endpoints for both types of
  /// user i.e. 1p and 3p, used to connect AGM/RM UI.
  public var workforceIdentityBasedManagementUri: WorkforceIdentityBasedManagementURI? = nil

  /// Output only. The ManagementServer state.
  public var state: ManagementServer.InstanceState = ManagementServer.InstanceState()

  /// Optional. VPC networks to which the ManagementServer instance is connected.
  /// For this version, only a single network is supported. This field is
  /// optional if MS is created without PSA
  public var networks: [NetworkConfig] = []

  /// Optional. Server specified ETag for the ManagementServer resource to
  /// prevent simultaneous updates from overwiting each other.
  public var etag: Swift.String = Swift.String()

  /// Output only. The OAuth 2.0 client id is required to make API calls to the
  /// BackupDR instance API of this ManagementServer. This is the value that
  /// should be provided in the 'aud' field of the OIDC ID Token (see openid
  /// specification
  /// https://openid.net/specs/openid-connect-core-1_0.html#IDToken).
  public var oauth2ClientId: Swift.String = Swift.String()

  /// Output only. The OAuth client IDs for both types of user i.e. 1p and 3p.
  public var workforceIdentityBasedOauth2ClientId: WorkforceIdentityBasedOAuth2ClientID? = nil

  /// Output only. The hostname or ip address of the exposed AGM endpoints, used
  /// by BAs to connect to BA proxy.
  public var baProxyUri: [Swift.String] = []

  /// Output only. Reserved for future use.
  public var satisfiesPzs: GoogleCloudWkt.BoolValue? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ManagementServer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ManagementServer().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of backup service resource.
  public enum InstanceType: Codable, Equatable, Sendable {
    /// Instance type is not mentioned.
    case unspecified
    /// Instance for backup and restore management (i.e., AGM).
    case backupRestore
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .backupRestore: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_TYPE_UNSPECIFIED"
      case .backupRestore: return "BACKUP_RESTORE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_TYPE_UNSPECIFIED": self = .unspecified
      case "BACKUP_RESTORE": self = .backupRestore
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .backupRestore
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .backupRestore: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of Management server instance.
  public enum InstanceState: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// The instance is being created.
    case creating
    /// The instance has been created and is fully usable.
    case ready
    /// The instance configuration is being updated. Certain kinds of updates
    /// may cause the instance to become unusable while the update is in
    /// progress.
    case updating
    /// The instance is being deleted.
    case deleting
    /// The instance is being repaired and may be unstable.
    case repairing
    /// Maintenance is being performed on this instance.
    case maintenance
    /// The instance is experiencing an issue and might be unusable. You can get
    /// further details from the statusMessage field of Instance resource.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 4
      case .repairing: return 5
      case .maintenance: return 6
      case .error: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .repairing: return "REPAIRING"
      case .maintenance: return "MAINTENANCE"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "REPAIRING": self = .repairing
      case "MAINTENANCE": self = .maintenance
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .repairing
      case 6: self = .maintenance
      case 7: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .repairing: return try container.encode(5)
      case .maintenance: return try container.encode(6)
      case .error: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ManagementServer"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
