// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ResourceBackupConfig represents a resource along with its backup
/// configurations.
public struct ResourceBackupConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the ResourceBackupConfig.
  /// Format:
  /// projects/{project}/locations/{location}/resourceBackupConfigs/{uid}
  public var name: Swift.String = Swift.String()

  /// Output only. The unique identifier of the resource backup config.
  public var uid: Swift.String = Swift.String()

  /// Output only. The [full resource
  /// name](https://cloud.google.com/asset-inventory/docs/resource-name-format)
  /// of the cloud resource that this configuration applies to. Supported
  /// resource types are
  /// [ResourceBackupConfig.ResourceType][google.cloud.backupdr.v1.ResourceBackupConfig.ResourceType].
  ///
  /// [google.cloud.backupdr.v1.ResourceBackupConfig.ResourceType]: <doc:ResourceBackupConfig/ResourceType>
  public var targetResource: Swift.String = Swift.String()

  /// Output only. The human friendly name of the target resource.
  public var targetResourceDisplayName: Swift.String = Swift.String()

  /// Output only. The type of the target resource.
  public var targetResourceType: ResourceBackupConfig.ResourceType =
    ResourceBackupConfig.ResourceType()

  /// Labels associated with the target resource.
  public var targetResourceLabels: [Swift.String: Swift.String] = [:]

  /// Backup configurations applying to the target resource, including those
  /// targeting its related/child resources. For example, backup configuration
  /// applicable to Compute Engine disks will be populated in this field for a
  /// Compute Engine VM which has the disk associated.
  public var backupConfigsDetails: [BackupConfigDetails] = []

  /// Output only. Whether the target resource is configured for backup. This is
  /// true if the backup_configs_details is not empty.
  public var backupConfigured: Swift.Bool = Swift.Bool()

  /// Output only. Whether the target resource is protected by a backup vault.
  /// This is true if the backup_configs_details is not empty and any of the
  /// [ResourceBackupConfig.backup_configs_details][google.cloud.backupdr.v1.ResourceBackupConfig.backup_configs_details]
  /// has a backup configuration with
  /// [BackupConfigDetails.backup_vault][google.cloud.backupdr.v1.BackupConfigDetails.backup_vault]
  /// set. set.
  ///
  /// [google.cloud.backupdr.v1.BackupConfigDetails.backup_vault]: <doc:BackupConfigDetails/backupVault>
  /// [google.cloud.backupdr.v1.ResourceBackupConfig.backup_configs_details]: <doc:ResourceBackupConfig/backupConfigsDetails>
  public var vaulted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ResourceBackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceBackupConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of the cloud resource.
  public enum ResourceType: Codable, Equatable, Sendable {
    /// Resource type not set.
    case unspecified
    /// Cloud SQL instance.
    case cloudSqlInstance
    /// Compute Engine VM.
    case computeEngineVm
    /// Compute Engine Disk.
    case computeEngineDisk
    /// Compute Engine Regional Disk.
    case computeEngineRegionalDisk
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudSqlInstance: return 1
      case .computeEngineVm: return 2
      case .computeEngineDisk: return 3
      case .computeEngineRegionalDisk: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESOURCE_TYPE_UNSPECIFIED"
      case .cloudSqlInstance: return "CLOUD_SQL_INSTANCE"
      case .computeEngineVm: return "COMPUTE_ENGINE_VM"
      case .computeEngineDisk: return "COMPUTE_ENGINE_DISK"
      case .computeEngineRegionalDisk: return "COMPUTE_ENGINE_REGIONAL_DISK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_SQL_INSTANCE": self = .cloudSqlInstance
      case "COMPUTE_ENGINE_VM": self = .computeEngineVm
      case "COMPUTE_ENGINE_DISK": self = .computeEngineDisk
      case "COMPUTE_ENGINE_REGIONAL_DISK": self = .computeEngineRegionalDisk
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudSqlInstance
      case 2: self = .computeEngineVm
      case 3: self = .computeEngineDisk
      case 4: self = .computeEngineRegionalDisk
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudSqlInstance: return try container.encode(1)
      case .computeEngineVm: return try container.encode(2)
      case .computeEngineDisk: return try container.encode(3)
      case .computeEngineRegionalDisk: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ResourceBackupConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
