// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for restoring from a Backup.
public struct RestoreBackupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Backup instance, in the format
  /// 'projects/*/locations/*/backupVaults/*/dataSources/*/backups/'.
  public var name: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. A field mask used to clear server-side default values
  /// for fields within the `instance_properties` oneof.
  ///
  /// When a field in this mask is cleared, the server will not apply its
  /// default logic (like inheriting a value from the source) for that field.
  ///
  /// The most common current use case is clearing default encryption keys.
  ///
  /// Examples of field mask paths:
  /// - Compute Instance Disks:
  /// `compute_instance_restore_properties.disks.*.disk_encryption_key`
  /// - Single Disk: `disk_restore_properties.disk_encryption_key`
  public var clearOverridesFieldMask: GoogleCloudWkt.FieldMask? = nil

  /// The target environment for the restore operation.
  public var targetEnvironment: OneOf_TargetEnvironment? = nil

  /// The property overrides for the instance being restored.
  public var instanceProperties: OneOf_InstanceProperties? = nil

  /// Initialize a new instance of `RestoreBackupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreBackupRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case requestId = "requestId"
    case computeInstanceTargetEnvironment = "computeInstanceTargetEnvironment"
    case diskTargetEnvironment = "diskTargetEnvironment"
    case regionDiskTargetEnvironment = "regionDiskTargetEnvironment"
    case computeInstanceRestoreProperties = "computeInstanceRestoreProperties"
    case diskRestoreProperties = "diskRestoreProperties"
    case clearOverridesFieldMask = "clearOverridesFieldMask"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.requestId = try container.decode(Swift.String.self, forKey: .requestId)
    self.clearOverridesFieldMask = try container.decodeIfPresent(
      GoogleCloudWkt.FieldMask.self, forKey: .clearOverridesFieldMask)

    var targetEnvironment: OneOf_TargetEnvironment? = nil
    let targetEnvironmentCheckAndSet = {
      if targetEnvironment != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetEnvironment'"))
      }
      targetEnvironment = $0
    }
    if let computeInstanceTargetEnvironment = try container.decodeIfPresent(
      ComputeInstanceTargetEnvironment?.self, forKey: .computeInstanceTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(
        .computeInstanceTargetEnvironment(computeInstanceTargetEnvironment))
    }
    if let diskTargetEnvironment = try container.decodeIfPresent(
      DiskTargetEnvironment?.self, forKey: .diskTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(.diskTargetEnvironment(diskTargetEnvironment))
    }
    if let regionDiskTargetEnvironment = try container.decodeIfPresent(
      RegionDiskTargetEnvironment?.self, forKey: .regionDiskTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(.regionDiskTargetEnvironment(regionDiskTargetEnvironment))
    }
    self.targetEnvironment = targetEnvironment

    var instanceProperties: OneOf_InstanceProperties? = nil
    let instancePropertiesCheckAndSet = {
      if instanceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'instanceProperties'"))
      }
      instanceProperties = $0
    }
    if let computeInstanceRestoreProperties = try container.decodeIfPresent(
      ComputeInstanceRestoreProperties?.self, forKey: .computeInstanceRestoreProperties)
    {
      try instancePropertiesCheckAndSet(
        .computeInstanceRestoreProperties(computeInstanceRestoreProperties))
    }
    if let diskRestoreProperties = try container.decodeIfPresent(
      DiskRestoreProperties?.self, forKey: .diskRestoreProperties)
    {
      try instancePropertiesCheckAndSet(.diskRestoreProperties(diskRestoreProperties))
    }
    self.instanceProperties = instanceProperties
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.clearOverridesFieldMask, forKey: .clearOverridesFieldMask)

    if let choice = self.targetEnvironment {
      switch choice {
      case .computeInstanceTargetEnvironment(let value):
        try container.encode(value, forKey: .computeInstanceTargetEnvironment)
      case .diskTargetEnvironment(let value):
        try container.encode(value, forKey: .diskTargetEnvironment)
      case .regionDiskTargetEnvironment(let value):
        try container.encode(value, forKey: .regionDiskTargetEnvironment)
      }
    }

    if let choice = self.instanceProperties {
      switch choice {
      case .computeInstanceRestoreProperties(let value):
        try container.encode(value, forKey: .computeInstanceRestoreProperties)
      case .diskRestoreProperties(let value):
        try container.encode(value, forKey: .diskRestoreProperties)
      }
    }
  }

  /// The target environment for the restore operation.
  public enum OneOf_TargetEnvironment: Codable, Equatable, Sendable {
    /// Compute Engine target environment to be used during restore.
    indirect case computeInstanceTargetEnvironment(ComputeInstanceTargetEnvironment?)
    /// Disk target environment to be used during restore.
    indirect case diskTargetEnvironment(DiskTargetEnvironment?)
    /// Region disk target environment to be used during restore.
    indirect case regionDiskTargetEnvironment(RegionDiskTargetEnvironment?)
  }

  /// The property overrides for the instance being restored.
  public enum OneOf_InstanceProperties: Codable, Equatable, Sendable {
    /// Compute Engine instance properties to be overridden during restore.
    indirect case computeInstanceRestoreProperties(ComputeInstanceRestoreProperties?)
    /// Disk properties to be overridden during restore.
    indirect case diskRestoreProperties(DiskRestoreProperties?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.RestoreBackupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
