// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// `WeekDayOfMonth` defines the week day of the month on which the backups will
/// run. The message combines a `WeekOfMonth` and `DayOfWeek` to produce values
/// like `FIRST`/`MONDAY` or `LAST`/`FRIDAY`.
public struct WeekDayOfMonth: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Specifies the week of the month.
  public var weekOfMonth: WeekDayOfMonth.WeekOfMonth = WeekDayOfMonth.WeekOfMonth()

  /// Required. Specifies the day of the week.
  public var dayOfWeek: GoogleType.DayOfWeek = GoogleType.DayOfWeek()

  /// Initialize a new instance of `WeekDayOfMonth`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WeekDayOfMonth().with { $0.weekOfMonth = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// `WeekOfMonth` enumerates possible weeks in the month, e.g. the first,
  /// third, or last week of the month.
  public enum WeekOfMonth: Codable, Equatable, Sendable {
    /// The zero value. Do not use.
    case unspecified
    /// The first week of the month.
    case first
    /// The second week of the month.
    case second
    /// The third week of the month.
    case third
    /// The fourth  week of the month.
    case fourth
    /// The last  week of the month.
    case last
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .first: return 1
      case .second: return 2
      case .third: return 3
      case .fourth: return 4
      case .last: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WEEK_OF_MONTH_UNSPECIFIED"
      case .first: return "FIRST"
      case .second: return "SECOND"
      case .third: return "THIRD"
      case .fourth: return "FOURTH"
      case .last: return "LAST"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WeekOfMonth/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WEEK_OF_MONTH_UNSPECIFIED": self = .unspecified
      case "FIRST": self = .first
      case "SECOND": self = .second
      case "THIRD": self = .third
      case "FOURTH": self = .fourth
      case "LAST": self = .last
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WeekOfMonth/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .first
      case 2: self = .second
      case 3: self = .third
      case 4: self = .fourth
      case 5: self = .last
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .first: return try container.encode(1)
      case .second: return try container.encode(2)
      case .third: return try container.encode(3)
      case .fourth: return try container.encode(4)
      case .last: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.WeekDayOfMonth"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
